apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test-deployment
  labels:
    group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
        - name: node-test
          image: emanuelbodin/node-test:1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
