apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 3
  template:
    spec:
      containers:
        - name: node-test
          image: emanuelbodin/node-test:2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: node-test
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
